library(data.table)
buck=fread("http://sars2.net/f/czbucketskeep.csv.gz")[dose<=1]
std=fread("http://sars2.net/f/czcensus2021pop.csv")$pop
t=buck[type!="Unvaccinated",.(dead=sum(dead),alive=sum(as.double(alive))),.(vaxmonth,type,age)]
t=rbind(t,t[,.(dead=sum(dead),alive=sum(alive),vaxmonth="Total"),.(type,age)])
totage=t[,.(age="Total",alive=sum(alive),asmr=sum(dead/alive*std[pmin(100,age)+1]/sum(std))),.(vaxmonth,type)]
t=t[,.(alive=sum(alive),asmr=sum(dead/alive*std[pmin(age,100)+1]/sum(std)*365e5)),.(vaxmonth,type,age=pmin(age%/%10*10,90))]
t=rbind(t,totage)
t[,.(ratio=asmr[type=="Moderna"]/asmr[type=="Pfizer"]),.(vaxmonth,age)]|>with(round(xtabs(ratio~vaxmonth+age),2))
